export const RIVERS_STATE_AREAS = [
    'Port Harcourt City',
    'Obio-Akpor',
    'Eleme',
    'Oyigbo',
    'Okrika',
    'Bonny',
    'Degema',
    'Ahoada East',
    'Ahoada West',
    'Abua/Odual',
    'Ogba/Egbema/Ndoni',
    'Etche',
    'Omuma',
    'Emohua',
    'Ikwerre',
    'Khana',
    'Gokana',
    'Tai',
    'Ogu/Bolo',
    'Asari-Toru',
    'Akuku-Toru',
    'Andoni',
    'Opobo/Nkoro',
    'Abonnema',
    'Buguma',
    'Rumuola',
    'Rumuokoro',
    'Trans-Amadi',
    'Diobu',
    'Mile 1',
    'Mile 2',
    'Mile 3',
    'Rumuigbo',
    'Woji',
    'Eliozu',
    'Rukpokwu',
    'Rumuodara',
    'Eneka',
    'Igwuruta',
    'Choba',
    'Alakahia',
    'Ozuoba',
    'Agbada',
    'Ogbogoro',
    'Rumuepirikom',
    'Eligbam',
    'Garrison',
    'Old GRA',
    'New GRA',
    'Peter Odili Road',
    'Abuloma',
    'Borokiri',
    'Aggrey Road',
    'Azikiwe Road',
    'Ada George Road',
    'Ikoku',
    'Waterlines',
    'Nkpolu-Oroworukwo',
    'Rumuobiakani',
    'Orazi',
    'Rumukrushi'
].sort();
